//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epilogger.Web.Epilogr {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Container", Namespace="http://epilo.gr")]
    [System.SerializableAttribute()]
    public partial class Container : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortenedUrlField;
        
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RealUrl {
            get {
                return this.RealUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.RealUrlField, value) != true)) {
                    this.RealUrlField = value;
                    this.RaisePropertyChanged("RealUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ShortenedUrl {
            get {
                return this.ShortenedUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortenedUrlField, value) != true)) {
                    this.ShortenedUrlField = value;
                    this.RaisePropertyChanged("ShortenedUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://epilo.gr", ConfigurationName="Epilogr.APISoap")]
    public interface APISoap {
        
        // CODEGEN: Generating message contract since element name realURL from namespace http://epilo.gr is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://epilo.gr/CreateUrl", ReplyAction="*")]
        Epilogger.Web.Epilogr.CreateUrlResponse CreateUrl(Epilogger.Web.Epilogr.CreateUrlRequest request);
        
        // CODEGEN: Generating message contract since element name shortURL from namespace http://epilo.gr is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://epilo.gr/GetUrl", ReplyAction="*")]
        Epilogger.Web.Epilogr.GetUrlResponse GetUrl(Epilogger.Web.Epilogr.GetUrlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUrl", Namespace="http://epilo.gr", Order=0)]
        public Epilogger.Web.Epilogr.CreateUrlRequestBody Body;
        
        public CreateUrlRequest() {
        }
        
        public CreateUrlRequest(Epilogger.Web.Epilogr.CreateUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://epilo.gr")]
    public partial class CreateUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string realURL;
        
        public CreateUrlRequestBody() {
        }
        
        public CreateUrlRequestBody(string realURL) {
            this.realURL = realURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUrlResponse", Namespace="http://epilo.gr", Order=0)]
        public Epilogger.Web.Epilogr.CreateUrlResponseBody Body;
        
        public CreateUrlResponse() {
        }
        
        public CreateUrlResponse(Epilogger.Web.Epilogr.CreateUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://epilo.gr")]
    public partial class CreateUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Epilogger.Web.Epilogr.Container CreateUrlResult;
        
        public CreateUrlResponseBody() {
        }
        
        public CreateUrlResponseBody(Epilogger.Web.Epilogr.Container CreateUrlResult) {
            this.CreateUrlResult = CreateUrlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUrl", Namespace="http://epilo.gr", Order=0)]
        public Epilogger.Web.Epilogr.GetUrlRequestBody Body;
        
        public GetUrlRequest() {
        }
        
        public GetUrlRequest(Epilogger.Web.Epilogr.GetUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://epilo.gr")]
    public partial class GetUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shortURL;
        
        public GetUrlRequestBody() {
        }
        
        public GetUrlRequestBody(string shortURL) {
            this.shortURL = shortURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUrlResponse", Namespace="http://epilo.gr", Order=0)]
        public Epilogger.Web.Epilogr.GetUrlResponseBody Body;
        
        public GetUrlResponse() {
        }
        
        public GetUrlResponse(Epilogger.Web.Epilogr.GetUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://epilo.gr")]
    public partial class GetUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Epilogger.Web.Epilogr.Container GetUrlResult;
        
        public GetUrlResponseBody() {
        }
        
        public GetUrlResponseBody(Epilogger.Web.Epilogr.Container GetUrlResult) {
            this.GetUrlResult = GetUrlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APISoapChannel : Epilogger.Web.Epilogr.APISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APISoapClient : System.ServiceModel.ClientBase<Epilogger.Web.Epilogr.APISoap>, Epilogger.Web.Epilogr.APISoap {
        
        public APISoapClient() {
        }
        
        public APISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Epilogger.Web.Epilogr.CreateUrlResponse Epilogger.Web.Epilogr.APISoap.CreateUrl(Epilogger.Web.Epilogr.CreateUrlRequest request) {
            return base.Channel.CreateUrl(request);
        }
        
        public Epilogger.Web.Epilogr.Container CreateUrl(string realURL) {
            Epilogger.Web.Epilogr.CreateUrlRequest inValue = new Epilogger.Web.Epilogr.CreateUrlRequest();
            inValue.Body = new Epilogger.Web.Epilogr.CreateUrlRequestBody();
            inValue.Body.realURL = realURL;
            Epilogger.Web.Epilogr.CreateUrlResponse retVal = ((Epilogger.Web.Epilogr.APISoap)(this)).CreateUrl(inValue);
            return retVal.Body.CreateUrlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Epilogger.Web.Epilogr.GetUrlResponse Epilogger.Web.Epilogr.APISoap.GetUrl(Epilogger.Web.Epilogr.GetUrlRequest request) {
            return base.Channel.GetUrl(request);
        }
        
        public Epilogger.Web.Epilogr.Container GetUrl(string shortURL) {
            Epilogger.Web.Epilogr.GetUrlRequest inValue = new Epilogger.Web.Epilogr.GetUrlRequest();
            inValue.Body = new Epilogger.Web.Epilogr.GetUrlRequestBody();
            inValue.Body.shortURL = shortURL;
            Epilogger.Web.Epilogr.GetUrlResponse retVal = ((Epilogger.Web.Epilogr.APISoap)(this)).GetUrl(inValue);
            return retVal.Body.GetUrlResult;
        }
    }
}
