// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Epilogger.Web.Controllers {
    public partial class BrowseController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BrowseController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected BrowseController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Index() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetBrowseOverviewTabData() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetBrowseOverviewTabData);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BrowseController Actions { get { return MVC.Browse; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Browse";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Browse";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string GetBrowseOverviewTabData = "GetBrowseOverviewTabData";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Index = "Index";
            public const string GetBrowseOverviewTabData = "GetBrowseOverviewTabData";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index {
            public readonly string filter = "filter";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_GetBrowseOverviewTabData s_params_GetBrowseOverviewTabData = new ActionParamsClass_GetBrowseOverviewTabData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetBrowseOverviewTabData GetBrowseOverviewTabDataParams { get { return s_params_GetBrowseOverviewTabData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetBrowseOverviewTabData {
            public readonly string Tab = "Tab";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _BrowseEventLists = "~/Views/Browse/_BrowseEventLists.cshtml";
            public readonly string _BrowseEventOverview = "~/Views/Browse/_BrowseEventOverview.cshtml";
            public readonly string _BrowseEventTabContentTemplate = "~/Views/Browse/_BrowseEventTabContentTemplate.cshtml";
            public readonly string Index = "~/Views/Browse/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_BrowseController: Epilogger.Web.Controllers.BrowseController {
        public T4MVC_BrowseController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index(string filter, int? page) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            callInfo.RouteValueDictionary.Add("filter", filter);
            callInfo.RouteValueDictionary.Add("page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetBrowseOverviewTabData(int Tab) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetBrowseOverviewTabData);
            callInfo.RouteValueDictionary.Add("Tab", Tab);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
