// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Epilogger.Web.Controllers {
    public partial class EventsController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EventsController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected EventsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Category() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Category);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Details() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AllPhotos() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AllPhotos);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AllTweets() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AllTweets);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EventBySlug() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.EventBySlug);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetImageComments() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetImageComments);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetLastTweetsJSON() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetLastTweetsJSON);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetLastPhotosJSON() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetLastPhotosJSON);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Subscribe() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Subscribe);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult UnSubscribe() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.UnSubscribe);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult eventRating() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.eventRating);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Search() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Search);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AllContent() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AllContent);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AllBlogPosts() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AllBlogPosts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AllCheckins() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AllCheckins);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AllLinks() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AllLinks);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AllStats() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AllStats);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Edit() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.PartialViewResult SearchVenues() {
            return new T4MVC_PartialViewResult(Area, Name, ActionNames.SearchVenues);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddBlogPost() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddBlogPost);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult UploadPhotos() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.UploadPhotos);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EventsController Actions { get { return MVC.Events; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Events";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Events";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Category = "Category";
            public readonly string Details = "Details";
            public readonly string AllPhotos = "AllPhotos";
            public readonly string AllTweets = "AllTweets";
            public readonly string Create = "Create";
            public readonly string EventBySlug = "EventBySlug";
            public readonly string GetImageComments = "GetImageComments";
            public readonly string GetLastTweetsJSON = "GetLastTweetsJSON";
            public readonly string GetLastPhotosJSON = "GetLastPhotosJSON";
            public readonly string Subscribe = "Subscribe";
            public readonly string UnSubscribe = "UnSubscribe";
            public readonly string eventRating = "eventRating";
            public readonly string Search = "Search";
            public readonly string AllContent = "AllContent";
            public readonly string AllBlogPosts = "AllBlogPosts";
            public readonly string AllCheckins = "AllCheckins";
            public readonly string AllLinks = "AllLinks";
            public readonly string AllStats = "AllStats";
            public readonly string Edit = "Edit";
            public readonly string VenueSearch = "VenueSearch";
            public readonly string SearchVenues = "SearchVenues";
            public readonly string AddBlogPost = "AddBlogPost";
            public readonly string AddLink = "AddLink";
            public readonly string StarRatings = "StarRatings";
            public readonly string UploadPhotos = "UploadPhotos";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Category = "Category";
            public const string Details = "Details";
            public const string AllPhotos = "AllPhotos";
            public const string AllTweets = "AllTweets";
            public const string Create = "Create";
            public const string EventBySlug = "EventBySlug";
            public const string GetImageComments = "GetImageComments";
            public const string GetLastTweetsJSON = "GetLastTweetsJSON";
            public const string GetLastPhotosJSON = "GetLastPhotosJSON";
            public const string Subscribe = "Subscribe";
            public const string UnSubscribe = "UnSubscribe";
            public const string eventRating = "eventRating";
            public const string Search = "Search";
            public const string AllContent = "AllContent";
            public const string AllBlogPosts = "AllBlogPosts";
            public const string AllCheckins = "AllCheckins";
            public const string AllLinks = "AllLinks";
            public const string AllStats = "AllStats";
            public const string Edit = "Edit";
            public const string VenueSearch = "VenueSearch";
            public const string SearchVenues = "SearchVenues";
            public const string AddBlogPost = "AddBlogPost";
            public const string AddLink = "AddLink";
            public const string StarRatings = "StarRatings";
            public const string UploadPhotos = "UploadPhotos";
        }


        static readonly ActionParamsClass_Category s_params_Category = new ActionParamsClass_Category();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Category CategoryParams { get { return s_params_Category; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Category {
            public readonly string CategoryName = "CategoryName";
        }
        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AllPhotos s_params_AllPhotos = new ActionParamsClass_AllPhotos();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AllPhotos AllPhotosParams { get { return s_params_AllPhotos; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AllPhotos {
            public readonly string id = "id";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_AllTweets s_params_AllTweets = new ActionParamsClass_AllTweets();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AllTweets AllTweetsParams { get { return s_params_AllTweets; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AllTweets {
            public readonly string id = "id";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_EventBySlug s_params_EventBySlug = new ActionParamsClass_EventBySlug();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EventBySlug EventBySlugParams { get { return s_params_EventBySlug; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EventBySlug {
            public readonly string eventSlug = "eventSlug";
        }
        static readonly ActionParamsClass_GetImageComments s_params_GetImageComments = new ActionParamsClass_GetImageComments();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetImageComments GetImageCommentsParams { get { return s_params_GetImageComments; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetImageComments {
            public readonly string eventId = "eventId";
            public readonly string imageid = "imageid";
        }
        static readonly ActionParamsClass_GetLastTweetsJSON s_params_GetLastTweetsJSON = new ActionParamsClass_GetLastTweetsJSON();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetLastTweetsJSON GetLastTweetsJSONParams { get { return s_params_GetLastTweetsJSON; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetLastTweetsJSON {
            public readonly string Count = "Count";
            public readonly string pageLoadTime = "pageLoadTime";
            public readonly string EventID = "EventID";
        }
        static readonly ActionParamsClass_GetLastPhotosJSON s_params_GetLastPhotosJSON = new ActionParamsClass_GetLastPhotosJSON();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetLastPhotosJSON GetLastPhotosJSONParams { get { return s_params_GetLastPhotosJSON; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetLastPhotosJSON {
            public readonly string Count = "Count";
            public readonly string pageLoadTime = "pageLoadTime";
            public readonly string EventID = "EventID";
        }
        static readonly ActionParamsClass_Subscribe s_params_Subscribe = new ActionParamsClass_Subscribe();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Subscribe SubscribeParams { get { return s_params_Subscribe; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Subscribe {
            public readonly string fc = "fc";
        }
        static readonly ActionParamsClass_UnSubscribe s_params_UnSubscribe = new ActionParamsClass_UnSubscribe();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UnSubscribe UnSubscribeParams { get { return s_params_UnSubscribe; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UnSubscribe {
            public readonly string fc = "fc";
        }
        static readonly ActionParamsClass_eventRating s_params_eventRating = new ActionParamsClass_eventRating();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_eventRating eventRatingParams { get { return s_params_eventRating; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_eventRating {
            public readonly string fc = "fc";
        }
        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search {
            public readonly string id = "id";
            public readonly string IEsearchterm = "IEsearchterm";
        }
        static readonly ActionParamsClass_AllContent s_params_AllContent = new ActionParamsClass_AllContent();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AllContent AllContentParams { get { return s_params_AllContent; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AllContent {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AllBlogPosts s_params_AllBlogPosts = new ActionParamsClass_AllBlogPosts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AllBlogPosts AllBlogPostsParams { get { return s_params_AllBlogPosts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AllBlogPosts {
            public readonly string id = "id";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_AllCheckins s_params_AllCheckins = new ActionParamsClass_AllCheckins();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AllCheckins AllCheckinsParams { get { return s_params_AllCheckins; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AllCheckins {
            public readonly string id = "id";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_AllLinks s_params_AllLinks = new ActionParamsClass_AllLinks();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AllLinks AllLinksParams { get { return s_params_AllLinks; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AllLinks {
            public readonly string id = "id";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_AllStats s_params_AllStats = new ActionParamsClass_AllStats();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AllStats AllStatsParams { get { return s_params_AllStats; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AllStats {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SearchVenues s_params_SearchVenues = new ActionParamsClass_SearchVenues();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SearchVenues SearchVenuesParams { get { return s_params_SearchVenues; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SearchVenues {
            public readonly string fc = "fc";
        }
        static readonly ActionParamsClass_AddBlogPost s_params_AddBlogPost = new ActionParamsClass_AddBlogPost();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddBlogPost AddBlogPostParams { get { return s_params_AddBlogPost; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddBlogPost {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UploadPhotos s_params_UploadPhotos = new ActionParamsClass_UploadPhotos();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadPhotos UploadPhotosParams { get { return s_params_UploadPhotos; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadPhotos {
            public readonly string id = "id";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _EventMenu = "~/Views/Events/_EventMenu.cshtml";
            public readonly string _ImageTemplate = "~/Views/Events/_ImageTemplate.cshtml";
            public readonly string _StarRatingTemplate = "~/Views/Events/_StarRatingTemplate.cshtml";
            public readonly string _TweetTemplate = "~/Views/Events/_TweetTemplate.cshtml";
            public readonly string _VenueSearchResults = "~/Views/Events/_VenueSearchResults.cshtml";
            public readonly string AddBlogPost = "~/Views/Events/AddBlogPost.cshtml";
            public readonly string AddLink = "~/Views/Events/AddLink.cshtml";
            public readonly string AllBlogPosts = "~/Views/Events/AllBlogPosts.cshtml";
            public readonly string AllCheckins = "~/Views/Events/AllCheckins.cshtml";
            public readonly string AllContent = "~/Views/Events/AllContent.cshtml";
            public readonly string AllLinks = "~/Views/Events/AllLinks.cshtml";
            public readonly string AllPhotos = "~/Views/Events/AllPhotos.cshtml";
            public readonly string AllStats = "~/Views/Events/AllStats.cshtml";
            public readonly string AllTweets = "~/Views/Events/AllTweets.cshtml";
            public readonly string Category = "~/Views/Events/Category.cshtml";
            public readonly string Create = "~/Views/Events/Create.cshtml";
            public readonly string Details = "~/Views/Events/Details.cshtml";
            public readonly string Edit = "~/Views/Events/Edit.cshtml";
            public readonly string EventToolbar = "~/Views/Events/EventToolbar.cshtml";
            public readonly string Menu = "~/Views/Events/Menu.cshtml";
            public readonly string Search = "~/Views/Events/Search.cshtml";
            public readonly string UploadPhotos = "~/Views/Events/UploadPhotos.cshtml";
            public readonly string VenueSearch = "~/Views/Events/VenueSearch.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_EventsController: Epilogger.Web.Controllers.EventsController {
        public T4MVC_EventsController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Category(string CategoryName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Category);
            callInfo.RouteValueDictionary.Add("CategoryName", CategoryName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Details(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Details);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Details(string id, System.Web.Mvc.FormCollection collection) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Details);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("collection", collection);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AllPhotos(string id, int? page) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AllPhotos);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AllTweets(string id, int? page) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AllTweets);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create(Epilogger.Web.Models.CreateEventViewModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EventBySlug(string eventSlug) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EventBySlug);
            callInfo.RouteValueDictionary.Add("eventSlug", eventSlug);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetImageComments(int eventId, int imageid) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetImageComments);
            callInfo.RouteValueDictionary.Add("eventId", eventId);
            callInfo.RouteValueDictionary.Add("imageid", imageid);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetLastTweetsJSON(int Count, string pageLoadTime, int EventID) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetLastTweetsJSON);
            callInfo.RouteValueDictionary.Add("Count", Count);
            callInfo.RouteValueDictionary.Add("pageLoadTime", pageLoadTime);
            callInfo.RouteValueDictionary.Add("EventID", EventID);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetLastPhotosJSON(int Count, string pageLoadTime, int EventID) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetLastPhotosJSON);
            callInfo.RouteValueDictionary.Add("Count", Count);
            callInfo.RouteValueDictionary.Add("pageLoadTime", pageLoadTime);
            callInfo.RouteValueDictionary.Add("EventID", EventID);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Subscribe(System.Web.Mvc.FormCollection fc) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Subscribe);
            callInfo.RouteValueDictionary.Add("fc", fc);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UnSubscribe(System.Web.Mvc.FormCollection fc) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UnSubscribe);
            callInfo.RouteValueDictionary.Add("fc", fc);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult eventRating(System.Web.Mvc.FormCollection fc) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.eventRating);
            callInfo.RouteValueDictionary.Add("fc", fc);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Search(string id, string IEsearchterm) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Search);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("IEsearchterm", IEsearchterm);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Search(System.Web.Mvc.FormCollection fc) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Search);
            callInfo.RouteValueDictionary.Add("fc", fc);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AllContent(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AllContent);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AllBlogPosts(string id, int? page) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AllBlogPosts);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AllCheckins(string id, int? page) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AllCheckins);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AllLinks(string id, int? page) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AllLinks);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AllStats(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AllStats);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(string id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(System.Web.Mvc.FormCollection fc, Epilogger.Web.Models.CreateEventViewModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("fc", fc);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult VenueSearch() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.VenueSearch);
            return callInfo;
        }

        public override System.Web.Mvc.PartialViewResult SearchVenues(System.Web.Mvc.FormCollection fc) {
            var callInfo = new T4MVC_PartialViewResult(Area, Name, ActionNames.SearchVenues);
            callInfo.RouteValueDictionary.Add("fc", fc);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddBlogPost(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddBlogPost);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddLink() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddLink);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult StarRatings() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.StarRatings);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult StarRatings(System.Web.Mvc.FormCollection fc) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.StarRatings);
            callInfo.RouteValueDictionary.Add("fc", fc);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UploadPhotos(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UploadPhotos);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
