// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Epilogger.Web.Controllers {
    public partial class JoinController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public JoinController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected JoinController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Facebook() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Facebook);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public JoinController Actions { get { return MVC.Join; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Join";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Join";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Signup = "Signup";
            public readonly string Twitter = "Twitter";
            public readonly string Facebook = "Facebook";
            public readonly string Email = "Email";
            public readonly string ResendVerificationEmail = "ResendVerificationEmail";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Signup = "Signup";
            public const string Twitter = "Twitter";
            public const string Facebook = "Facebook";
            public const string Email = "Email";
            public const string ResendVerificationEmail = "ResendVerificationEmail";
        }


        static readonly ActionParamsClass_Facebook s_params_Facebook = new ActionParamsClass_Facebook();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Facebook FacebookParams { get { return s_params_Facebook; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Facebook {
            public readonly string returnUrl = "returnUrl";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _FullCreateForm = "~/Views/Join/_FullCreateForm.cshtml";
            public readonly string _ShortCreateForm = "~/Views/Join/_ShortCreateForm.cshtml";
            public readonly string Email = "~/Views/Join/Email.cshtml";
            public readonly string Facebook = "~/Views/Join/Facebook.cshtml";
            public readonly string Signup = "~/Views/Join/Signup.cshtml";
            public readonly string Twitter = "~/Views/Join/Twitter.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_JoinController: Epilogger.Web.Controllers.JoinController {
        public T4MVC_JoinController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Signup() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Signup);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Twitter() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Twitter);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Twitter(Epilogger.Web.Models.CreateAccountModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Twitter);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Facebook(string returnUrl) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Facebook);
            callInfo.RouteValueDictionary.Add("returnUrl", returnUrl);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Facebook(Epilogger.Web.Models.CreateAccountModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Facebook);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Email() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Email);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Email(Epilogger.Web.Models.CreateAccountModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Email);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ResendVerificationEmail() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ResendVerificationEmail);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
