// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Epilogger.Web.Controllers {
    public partial class NavigationController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public NavigationController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected NavigationController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public NavigationController Actions { get { return MVC.Navigation; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Navigation";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Navigation";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string GlobalNavigation = "GlobalNavigation";
            public readonly string Nag = "Nag";
            public readonly string GetNavMenu = "GetNavMenu";
            public readonly string RenderBreadCrumb = "RenderBreadCrumb";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string GlobalNavigation = "GlobalNavigation";
            public const string Nag = "Nag";
            public const string GetNavMenu = "GetNavMenu";
            public const string RenderBreadCrumb = "RenderBreadCrumb";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_NavigationController: Epilogger.Web.Controllers.NavigationController {
        public T4MVC_NavigationController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult GlobalNavigation() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GlobalNavigation);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Nag() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Nag);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetNavMenu() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetNavMenu);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RenderBreadCrumb() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RenderBreadCrumb);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
