// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC {
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _HomepageLayout = "~/Views/Shared/_HomepageLayout.cshtml";
            public readonly string _ImageComments = "~/Views/Shared/_ImageComments.cshtml";
            public readonly string _InteriorLayout = "~/Views/Shared/_InteriorLayout.cshtml";
            public readonly string _InteriorLayoutNoBC = "~/Views/Shared/_InteriorLayoutNoBC.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _ModalLayoutOLD = "~/Views/Shared/_ModalLayoutOLD.cshtml";
            public readonly string _PopupLayout = "~/Views/Shared/_PopupLayout.cshtml";
            public readonly string Breadcrumb = "~/Views/Shared/Breadcrumb.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string GlobalNavigation = "~/Views/Shared/GlobalNavigation.cshtml";
            public readonly string GlobalNavigationOldGood = "~/Views/Shared/GlobalNavigationOldGood.cshtml";
            public readonly string Nag = "~/Views/Shared/Nag.cshtml";
            public readonly string Navigation = "~/Views/Shared/Navigation.cshtml";
            public readonly string NavigationOldGood = "~/Views/Shared/NavigationOldGood.cshtml";
            static readonly _DisplayTemplates s_DisplayTemplates = new _DisplayTemplates();
            public _DisplayTemplates DisplayTemplates { get { return s_DisplayTemplates; } }
            public partial class _DisplayTemplates{
                public readonly string DateTime = "DateTime";
                public readonly string Day = "Day";
                public readonly string FullDate = "FullDate";
                public readonly string FullTime = "FullTime";
                public readonly string Month = "Month";
                public readonly string ShortDate = "ShortDate";
                public readonly string ShortDateTime = "ShortDateTime";
                public readonly string Time = "Time";
            }
            static readonly _EditorTemplates s_EditorTemplates = new _EditorTemplates();
            public _EditorTemplates EditorTemplates { get { return s_EditorTemplates; } }
            public partial class _EditorTemplates{
                public readonly string DateTime = "DateTime";
                public readonly string TimeSpan = "TimeSpan";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
