// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Epilogger.Web.Controllers {
    public partial class UtilitiesController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UtilitiesController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UtilitiesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Autocomplete() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Autocomplete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Autocomplete2() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Autocomplete2);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UtilitiesController Actions { get { return MVC.Utilities; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Utilities";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Utilities";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Autocomplete = "Autocomplete";
            public readonly string Autocomplete2 = "Autocomplete2";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Autocomplete = "Autocomplete";
            public const string Autocomplete2 = "Autocomplete2";
        }


        static readonly ActionParamsClass_Autocomplete s_params_Autocomplete = new ActionParamsClass_Autocomplete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Autocomplete AutocompleteParams { get { return s_params_Autocomplete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Autocomplete {
            public readonly string term = "term";
        }
        static readonly ActionParamsClass_Autocomplete2 s_params_Autocomplete2 = new ActionParamsClass_Autocomplete2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Autocomplete2 Autocomplete2Params { get { return s_params_Autocomplete2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Autocomplete2 {
            public readonly string term = "term";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_UtilitiesController: Epilogger.Web.Controllers.UtilitiesController {
        public T4MVC_UtilitiesController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Autocomplete(string term) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Autocomplete);
            callInfo.RouteValueDictionary.Add("term", term);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Autocomplete2(string term) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Autocomplete2);
            callInfo.RouteValueDictionary.Add("term", term);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
