//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epilogger.Web.Views.Emails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountEmails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountEmails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epilogger.Web.Views.Emails.AccountEmails", typeof(AccountEmails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;
        ///    &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt; 
        ///    
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;title&gt;Welcome to Epilogger.com&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    
        ///        /* Client-specific Styles */
        ///        #outlook a { padding: 0; } /* Force Outlook to provide a &quot;view in browser&quot; button. */
        ///        body { width: 100% !importan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdminEventCreated {
            get {
                return ResourceManager.GetString("AdminEventCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;
        ///    &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt; 
        ///    
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;title&gt;Welcome to Epilogger.com&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    
        ///        /* Client-specific Styles */
        ///        #outlook a { padding: 0; } /* Force Outlook to provide a &quot;view in browser&quot; button. */
        ///        body { width: 100% !importan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;
        ///    &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt; 
        ///    
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;title&gt;Welcome to Epilogger.com&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    
        ///        /* Client-specific Styles */
        ///        #outlook a { padding: 0; } /* Force Outlook to provide a &quot;view in browser&quot; button. */
        ///        body { width: 100% !importan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OldBetaInvite {
            get {
                return ResourceManager.GetString("OldBetaInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;
        ///    &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt; 
        ///    
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;title&gt;Welcome to Epilogger.com&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    
        ///        /* Client-specific Styles */
        ///        #outlook a { padding: 0; } /* Force Outlook to provide a &quot;view in browser&quot; button. */
        ///        body { width: 100% !importan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OldValidateAccount {
            get {
                return ResourceManager.GetString("OldValidateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi [FULLNAME]&lt;br /&gt;&lt;br /&gt;
        ///
        ///Thank you for registering and taking part in epilogger.com, the new hot way to remember your life.
        ///
        ///&lt;a href=&quot;[LINKTOLOGIN]&quot;&gt;Login and start epilogging!&lt;/a&gt;.
        /// </summary>
        internal static string OldWelcomeMessage {
            get {
                return ResourceManager.GetString("OldWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt; 
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///	&lt;title&gt;Verification&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		/* Based on The MailChimp Reset INLINE: Yes. */  
        ///		/* Client-specific Styles */
        ///		#outlook a {padding:0;} /* Force Outlook to provide a &quot;view in brow [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidateEmail {
            get {
                return ResourceManager.GetString("ValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt; 
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///	&lt;title&gt;Verification&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		/* Based on The MailChimp Reset INLINE: Yes. */  
        ///		/* Client-specific Styles */
        ///		#outlook a {padding:0;} /* Force Outlook to provide a &quot;view in brow [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidateEmailThankYou {
            get {
                return ResourceManager.GetString("ValidateEmailThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt; 
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///	&lt;title&gt;Welcome to Epilogger!&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		/* Based on The MailChimp Reset INLINE: Yes. */  
        ///		/* Client-specific Styles */
        ///		#outlook a {padding:0;} /* Force Outlook to provide a &quot;vie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WelcomeEmail {
            get {
                return ResourceManager.GetString("WelcomeEmail", resourceCulture);
            }
        }
    }
}
